### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by macmule** [dataJAR/jamJAR#16]
```
postflight stderr: Traceback (most recent call last):
  File "/usr/local/munki/postflight", line 365, in <module>
    main()
  File "/usr/local/munki/postflight", line 83, in main
    process_pending(pending_items)
  File "/usr/local/munki/postflight", line 147, in process_pending
    send_pending_notification(NOTIFIER_MSG_PENDING)
  File "/usr/local/munki/postflight", line 208, in send_pending_notification
    the_msg, NOTIFIER_MSG_TITLE,)]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdf' in position 36: ordinal not in range(128)
```

From jamJAR.plist:

```
	<key>notifier_msg_pending</key>
	<string>Bitte ausloggen um Update abzuschließen</string>
```

**Comment by macmule** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [jamJAR - UnicodeEncodeError](https://trello.com/c/e6ckEz7h/21-jamjar-unicodeencodeerror)

**Comment by macmule** [comment]
Closing as believed resolved.
